title: Plugo.io Data
email: plugo@captnemo.in
description: >
  Easily accessible website detailing where all plugo powerbanks are available.
theme: minima
baseurl: /plugo/
url: https://captnemo.in
timezone: Asia/Kolkata